/**
 * Labeled fixture corpus for the AI-attribution benchmark harness
 * (see `aiAttributionBenchmark.ts` and `__tests__/lib/aiAttributionBenchmark.test.ts`).
 *
 * HUMAN samples are verbatim excerpts from real, well-known open-source
 * libraries (zod, DOMPurify, entities) that predate widespread LLM-assisted
 * coding and were written/reviewed by human maintainers.
 *
 * AI samples were freshly generated by Claude (this assistant) for this
 * benchmark, in typical LLM-assistant style: heavy per-function JSDoc,
 * uniform try/catch with console.error, `{ success, data, error }` result
 * shapes, defensive null checks, and generic naming.
 *
 * This is a small (n=10), TS/JS-only internal benchmark — not a substitute
 * for a large labeled corpus, but it gives concrete precision/recall/F1/AUC
 * numbers instead of none.
 */

export type BenchmarkLabel = "human" | "ai";

export interface BenchmarkSample {
  id:       string;
  label:    BenchmarkLabel;
  language: string;
  source:   string;  // provenance note
  content:  string;
}

// ── Human-written samples (real OSS excerpts) ──────────────────────────────

const ZOD_UTIL_JS = `export var util;
(function (util) {
    util.assertEqual = (_) => { };
    function assertIs(_arg) { }
    util.assertIs = assertIs;
    function assertNever(_x) {
        throw new Error();
    }
    util.assertNever = assertNever;
    util.arrayToEnum = (items) => {
        const obj = {};
        for (const item of items) {
            obj[item] = item;
        }
        return obj;
    };
    util.getValidEnumValues = (obj) => {
        const validKeys = util.objectKeys(obj).filter((k) => typeof obj[obj[k]] !== "number");
        const filtered = {};
        for (const k of validKeys) {
            filtered[k] = obj[k];
        }
        return util.objectValues(filtered);
    };
    util.objectValues = (obj) => {
        return util.objectKeys(obj).map(function (e) {
            return obj[e];
        });
    };
    util.objectKeys = typeof Object.keys === "function"
        ? (obj) => Object.keys(obj)
        : (object) => {
            const keys = [];
            for (const key in object) {
                if (Object.prototype.hasOwnProperty.call(object, key)) {
                    keys.push(key);
                }
            }
            return keys;
        };
    util.find = (arr, checker) => {
        for (const item of arr) {
            if (checker(item))
                return item;
        }
        return undefined;
    };
    util.isInteger = typeof Number.isInteger === "function"
        ? (val) => Number.isInteger(val)
        : (val) => typeof val === "number" && Number.isFinite(val) && Math.floor(val) === val;
    function joinValues(array, separator = " | ") {
        return array.map((val) => (typeof val === "string" ? \`'\${val}'\` : val)).join(separator);
    }
    util.joinValues = joinValues;
    util.jsonStringifyReplacer = (_, value) => {
        if (typeof value === "bigint") {
            return value.toString();
        }
        return value;
    };
})(util || (util = {}));
export var objectUtil;
(function (objectUtil) {
    objectUtil.mergeShapes = (first, second) => {
        return {
            ...first,
            ...second,
        };
    };
})(objectUtil || (objectUtil = {}));
export const ZodParsedType = util.arrayToEnum([
    "string", "nan", "number", "integer", "float", "boolean", "date", "bigint",
    "symbol", "function", "undefined", "null", "array", "object", "unknown",
    "promise", "void", "never", "map", "set",
]);
export const getParsedType = (data) => {
    const t = typeof data;
    switch (t) {
        case "undefined": return ZodParsedType.undefined;
        case "string": return ZodParsedType.string;
        case "number": return Number.isNaN(data) ? ZodParsedType.nan : ZodParsedType.number;
        case "boolean": return ZodParsedType.boolean;
        case "function": return ZodParsedType.function;
        case "bigint": return ZodParsedType.bigint;
        case "symbol": return ZodParsedType.symbol;
        case "object":
            if (Array.isArray(data)) return ZodParsedType.array;
            if (data === null) return ZodParsedType.null;
            if (data.then && typeof data.then === "function" && data.catch && typeof data.catch === "function") return ZodParsedType.promise;
            if (typeof Map !== "undefined" && data instanceof Map) return ZodParsedType.map;
            if (typeof Set !== "undefined" && data instanceof Set) return ZodParsedType.set;
            if (typeof Date !== "undefined" && data instanceof Date) return ZodParsedType.date;
            return ZodParsedType.object;
        default: return ZodParsedType.unknown;
    }
};
`;

const ZOD_PARSEUTIL_JS = `import { getErrorMap } from "../errors.js";
import defaultErrorMap from "../locales/en.js";

export const makeIssue = (params) => {
    const { data, path, errorMaps, issueData } = params;
    const fullPath = [...path, ...(issueData.path || [])];
    const fullIssue = {
        ...issueData,
        path: fullPath,
    };
    if (issueData.message !== undefined) {
        return {
            ...issueData,
            path: fullPath,
            message: issueData.message,
        };
    }
    let errorMessage = "";
    const maps = errorMaps
        .filter((m) => !!m)
        .slice()
        .reverse();
    for (const map of maps) {
        errorMessage = map(fullIssue, { data, defaultError: errorMessage }).message;
    }
    return {
        ...issueData,
        path: fullPath,
        message: errorMessage,
    };
};
export const EMPTY_PATH = [];
export function addIssueToContext(ctx, issueData) {
    const overrideMap = getErrorMap();
    const issue = makeIssue({
        issueData: issueData,
        data: ctx.data,
        path: ctx.path,
        errorMaps: [
            ctx.common.contextualErrorMap,
            ctx.schemaErrorMap,
            overrideMap,
            overrideMap === defaultErrorMap ? undefined : defaultErrorMap,
        ].filter((x) => !!x),
    });
    ctx.common.issues.push(issue);
}
export class ParseStatus {
    constructor() {
        this.value = "valid";
    }
    dirty() {
        if (this.value === "valid")
            this.value = "dirty";
    }
    abort() {
        if (this.value !== "aborted")
            this.value = "aborted";
    }
    static mergeArray(status, results) {
        const arrayValue = [];
        for (const s of results) {
            if (s.status === "aborted")
                return INVALID;
            if (s.status === "dirty")
                status.dirty();
            arrayValue.push(s.value);
        }
        return { status: status.value, value: arrayValue };
    }
    static async mergeObjectAsync(status, pairs) {
        const syncPairs = [];
        for (const pair of pairs) {
            const key = await pair.key;
            const value = await pair.value;
            syncPairs.push({ key, value });
        }
        return ParseStatus.mergeObjectSync(status, syncPairs);
    }
    static mergeObjectSync(status, pairs) {
        const finalObject = {};
        for (const pair of pairs) {
            const { key, value } = pair;
            if (key.status === "aborted")
                return INVALID;
            if (value.status === "aborted")
                return INVALID;
            if (key.status === "dirty")
                status.dirty();
            if (value.status === "dirty")
                status.dirty();
            if (key.value !== "__proto__" && (typeof value.value !== "undefined" || pair.alwaysSet)) {
                finalObject[key.value] = value.value;
            }
        }
        return { status: status.value, value: finalObject };
    }
}
export const INVALID = Object.freeze({ status: "aborted" });
export const DIRTY = (value) => ({ status: "dirty", value });
export const OK = (value) => ({ status: "valid", value });
export const isAborted = (x) => x.status === "aborted";
export const isDirty = (x) => x.status === "dirty";
export const isValid = (x) => x.status === "valid";
export const isAsync = (x) => typeof Promise !== "undefined" && x instanceof Promise;
`;

const DOMPURIFY_UTILS_TS = `const {
  entries,
  setPrototypeOf,
  isFrozen,
  getPrototypeOf,
  getOwnPropertyDescriptor,
} = Object;

let { freeze, seal, create } = Object;
let { apply, construct } = typeof Reflect !== 'undefined' && Reflect;

if (!freeze) {
  freeze = function <T>(x: T): T {
    return x;
  };
}

if (!seal) {
  seal = function <T>(x: T): T {
    return x;
  };
}

if (!apply) {
  apply = function <T>(
    func: (thisArg: any, ...args: any[]) => T,
    thisArg: any,
    ...args: any[]
  ): T {
    return func.apply(thisArg, args);
  };
}

if (!construct) {
  construct = function <T>(Func: new (...args: any[]) => T, ...args: any[]): T {
    return new Func(...args);
  };
}

const arrayForEach = unapply(Array.prototype.forEach);
const arrayPop = unapply(Array.prototype.pop);
const arrayPush = unapply(Array.prototype.push);
const arraySlice = unapply(Array.prototype.slice);
const arrayIsArray = Array.isArray;

const stringToLowerCase = unapply(String.prototype.toLowerCase);
const stringMatch = unapply(String.prototype.match);
const stringReplace = unapply(String.prototype.replace);
const stringTrim = unapply(String.prototype.trim);

const objectHasOwnProperty = unapply(Object.prototype.hasOwnProperty);
const objectToString = unapply(Object.prototype.toString);

const regExpTest = unapply(RegExp.prototype.test);

function unapply<T>(
  func: (thisArg: any, ...args: any[]) => T
): (thisArg: any, ...args: any[]) => T {
  return (thisArg: any, ...args: any[]): T => {
    if (thisArg instanceof RegExp) {
      thisArg.lastIndex = 0;
    }

    return apply(func, thisArg, args);
  };
}

function addToSet(
  set: Record<string, boolean>,
  array: readonly unknown[],
  transformCaseFunc: ReturnType<typeof unapply<string>> = stringToLowerCase
): Record<string, boolean> {
  if (setPrototypeOf) {
    setPrototypeOf(set, null);
  }

  if (!arrayIsArray(array)) {
    return set;
  }

  let l = array.length;
  while (l--) {
    let element = array[l];

    if (typeof element === 'string') {
      const lcElement = transformCaseFunc(element);

      if (lcElement !== element) {
        if (!isFrozen(array)) {
          (array as unknown[])[l] = lcElement;
        }

        element = lcElement;
      }
    }

    set[element as string] = true;
  }

  return set;
}

function cleanArray<T>(array: T[]): Array<T | null> {
  for (let index = 0; index < array.length; index++) {
    const isPropertyExist = objectHasOwnProperty(array, index);

    if (!isPropertyExist) {
      array[index] = null;
    }
  }

  return array;
}

function clone<T extends Record<string, any>>(object: T): T {
  const newObject = create(null);

  for (const [property, value] of entries(object)) {
    const isPropertyExist = objectHasOwnProperty(object, property);

    if (isPropertyExist) {
      if (arrayIsArray(value)) {
        newObject[property] = cleanArray(value);
      } else if (
        value &&
        typeof value === 'object' &&
        value.constructor === Object
      ) {
        newObject[property] = clone(value);
      } else {
        newObject[property] = value;
      }
    }
  }

  return newObject;
}

function isRegex(value: unknown): value is RegExp {
  try {
    regExpTest(value as RegExp, '');
    return true;
  } catch {
    return false;
  }
}

export {
  arrayForEach,
  arrayIsArray,
  arrayPop,
  arrayPush,
  arraySlice,
  entries,
  freeze,
  getPrototypeOf,
  getOwnPropertyDescriptor,
  isFrozen,
  setPrototypeOf,
  seal,
  clone,
  create,
  objectHasOwnProperty,
  objectToString,
  regExpTest,
  isRegex,
  stringMatch,
  stringReplace,
  stringToLowerCase,
  stringTrim,
  unapply,
  addToSet,
};
`;

const ENTITIES_ESCAPE_TS = `export const xmlReplacer: RegExp = /["$&'<>\\u0080-\\uFFFF]/g;

const xmlCodeMap = new Map([
    [34, "&quot;"],
    [38, "&amp;"],
    [39, "&apos;"],
    [60, "&lt;"],
    [62, "&gt;"],
]);

export const getCodePoint: (c: string, index: number) => number =
    String.prototype.codePointAt == null
        ? (c: string, index: number): number =>
              (c.charCodeAt(index) & 0xfc_00) === 0xd8_00
                  ? (c.charCodeAt(index) - 0xd8_00) * 0x4_00 +
                    c.charCodeAt(index + 1) -
                    0xdc_00 +
                    0x1_00_00
                  : c.charCodeAt(index)
        : (input: string, index: number): number => input.codePointAt(index)!;

export function encodeXML(input: string): string {
    let returnValue = "";
    let lastIndex = 0;
    let match;

    while ((match = xmlReplacer.exec(input)) !== null) {
        const { index } = match;
        const char = input.charCodeAt(index);
        const next = xmlCodeMap.get(char);

        if (next === undefined) {
            returnValue += \`\${input.substring(lastIndex, index)}&#x\${getCodePoint(
                input,
                index,
            ).toString(16)};\`;
            lastIndex = xmlReplacer.lastIndex += Number(
                (char & 0xfc_00) === 0xd8_00,
            );
        } else {
            returnValue += input.substring(lastIndex, index) + next;
            lastIndex = index + 1;
        }
    }

    return returnValue + input.substr(lastIndex);
}

export const escape: typeof encodeXML = encodeXML;

function getEscaper(
    regex: RegExp,
    map: Map<number, string>,
): (data: string) => string {
    return function escape(data: string): string {
        let match;
        let lastIndex = 0;
        let result = "";

        while ((match = regex.exec(data))) {
            if (lastIndex !== match.index) {
                result += data.substring(lastIndex, match.index);
            }

            result += map.get(match[0].charCodeAt(0))!;
            lastIndex = match.index + 1;
        }

        return result + data.substring(lastIndex);
    };
}

export const escapeUTF8: (data: string) => string = getEscaper(
    /["&'<>]/g,
    xmlCodeMap,
);

export const escapeAttribute: (data: string) => string = getEscaper(
    /["&\\u00A0]/g,
    new Map([
        [34, "&quot;"],
        [38, "&amp;"],
        [160, "&nbsp;"],
    ]),
);

export const escapeText: (data: string) => string = getEscaper(
    /[&<>\\u00A0]/g,
    new Map([
        [38, "&amp;"],
        [60, "&lt;"],
        [62, "&gt;"],
        [160, "&nbsp;"],
    ]),
);
`;

const ZOD_ZODERROR_JS = `import { util } from "./helpers/util.js";

export const ZodIssueCode = util.arrayToEnum([
    "invalid_type", "invalid_literal", "custom", "invalid_union",
    "invalid_union_discriminator", "invalid_enum_value", "unrecognized_keys",
    "invalid_arguments", "invalid_return_type", "invalid_date", "invalid_string",
    "too_small", "too_big", "invalid_intersection_types", "not_multiple_of", "not_finite",
]);

export const quotelessJson = (obj) => {
    const json = JSON.stringify(obj, null, 2);
    return json.replace(/"([^"]+)":/g, "$1:");
};

export class ZodError extends Error {
    get errors() {
        return this.issues;
    }
    constructor(issues) {
        super();
        this.issues = [];
        this.addIssue = (sub) => {
            this.issues = [...this.issues, sub];
        };
        this.addIssues = (subs = []) => {
            this.issues = [...this.issues, ...subs];
        };
        const actualProto = new.target.prototype;
        if (Object.setPrototypeOf) {
            Object.setPrototypeOf(this, actualProto);
        }
        else {
            this.__proto__ = actualProto;
        }
        this.name = "ZodError";
        this.issues = issues;
    }
    format(_mapper) {
        const mapper = _mapper || function (issue) { return issue.message; };
        const fieldErrors = { _errors: [] };
        const processError = (error) => {
            for (const issue of error.issues) {
                if (issue.code === "invalid_union") {
                    issue.unionErrors.map(processError);
                }
                else if (issue.code === "invalid_return_type") {
                    processError(issue.returnTypeError);
                }
                else if (issue.code === "invalid_arguments") {
                    processError(issue.argumentsError);
                }
                else if (issue.path.length === 0) {
                    fieldErrors._errors.push(mapper(issue));
                }
                else {
                    let curr = fieldErrors;
                    let i = 0;
                    while (i < issue.path.length) {
                        const el = issue.path[i];
                        const terminal = i === issue.path.length - 1;
                        if (!terminal) {
                            curr[el] = curr[el] || { _errors: [] };
                        }
                        else {
                            curr[el] = curr[el] || { _errors: [] };
                            curr[el]._errors.push(mapper(issue));
                        }
                        curr = curr[el];
                        i++;
                    }
                }
            }
        };
        processError(this);
        return fieldErrors;
    }
    static assert(value) {
        if (!(value instanceof ZodError)) {
            throw new Error(\`Not a ZodError: \${value}\`);
        }
    }
    toString() {
        return this.message;
    }
    get message() {
        return JSON.stringify(this.issues, util.jsonStringifyReplacer, 2);
    }
    get isEmpty() {
        return this.issues.length === 0;
    }
    flatten(mapper = (issue) => issue.message) {
        const fieldErrors = Object.create(null);
        const formErrors = [];
        for (const sub of this.issues) {
            if (sub.path.length > 0) {
                const firstEl = sub.path[0];
                fieldErrors[firstEl] = fieldErrors[firstEl] || [];
                fieldErrors[firstEl].push(mapper(sub));
            }
            else {
                formErrors.push(mapper(sub));
            }
        }
        return { formErrors, fieldErrors };
    }
    get formErrors() {
        return this.flatten();
    }
}
ZodError.create = (issues) => {
    const error = new ZodError(issues);
    return error;
};
`;

// ── AI-generated samples (written fresh by Claude for this benchmark) ──────

const AI_VALIDATION_SERVICE_TS = `import { z } from "zod";

/**
 * Result of a validation operation.
 */
export interface ValidationResult<T> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Schema for validating a user registration request.
 */
const userRegistrationSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
  displayName: z.string().min(1).max(100),
  age: z.number().int().positive().optional(),
});

export type UserRegistrationInput = z.infer<typeof userRegistrationSchema>;

/**
 * Validates a user registration payload against the schema.
 *
 * @param input - The raw input to validate.
 * @returns A ValidationResult containing the parsed data or an error message.
 */
export function validateUserRegistration(input: unknown): ValidationResult<UserRegistrationInput> {
  try {
    const data = userRegistrationSchema.parse(input);
    return { success: true, data };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return { success: false, error: error.errors.map((e) => e.message).join(", ") };
    }
    console.error("Unexpected error during validation:", error);
    return { success: false, error: "An unexpected error occurred during validation." };
  }
}

/**
 * Schema for validating a profile update request.
 */
const profileUpdateSchema = z.object({
  displayName: z.string().min(1).max(100).optional(),
  bio: z.string().max(500).optional(),
  avatarUrl: z.string().url().optional(),
});

export type ProfileUpdateInput = z.infer<typeof profileUpdateSchema>;

/**
 * Validates a profile update payload against the schema.
 *
 * @param input - The raw input to validate.
 * @returns A ValidationResult containing the parsed data or an error message.
 */
export function validateProfileUpdate(input: unknown): ValidationResult<ProfileUpdateInput> {
  try {
    const data = profileUpdateSchema.parse(input);
    return { success: true, data };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return { success: false, error: error.errors.map((e) => e.message).join(", ") };
    }
    console.error("Unexpected error during validation:", error);
    return { success: false, error: "An unexpected error occurred during validation." };
  }
}

/**
 * Helper function to check whether a string is a valid email address.
 *
 * @param value - The string to check.
 * @returns True if the string is a valid email address, false otherwise.
 */
export function isValidEmail(value: string): boolean {
  if (!value) {
    return false;
  }
  try {
    z.string().email().parse(value);
    return true;
  } catch {
    return false;
  }
}

/**
 * Helper function to check whether a password meets the minimum strength
 * requirements.
 *
 * @param value - The password to check.
 * @returns True if the password is strong enough, false otherwise.
 */
export function isStrongPassword(value: string): boolean {
  if (!value || value.length < 8) {
    return false;
  }
  const hasUppercase = /[A-Z]/.test(value);
  const hasLowercase = /[a-z]/.test(value);
  const hasNumber = /[0-9]/.test(value);
  return hasUppercase && hasLowercase && hasNumber;
}
`;

const AI_API_CLIENT_TS = `/**
 * A lightweight wrapper around the fetch API for communicating with the
 * orders microservice. Provides automatic retries and consistent error
 * handling for all requests.
 */

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  statusCode?: number;
}

export interface OrderApiClientOptions {
  baseUrl: string;
  apiKey: string;
  maxRetries?: number;
  timeoutMs?: number;
}

export class OrderApiClient {
  private baseUrl: string;
  private apiKey: string;
  private maxRetries: number;
  private timeoutMs: number;

  /**
   * Creates a new instance of the OrderApiClient.
   *
   * @param options - Configuration options for the client.
   */
  constructor(options: OrderApiClientOptions) {
    this.baseUrl = options.baseUrl;
    this.apiKey = options.apiKey;
    this.maxRetries = options.maxRetries ?? 3;
    this.timeoutMs = options.timeoutMs ?? 5000;
  }

  /**
   * Fetches an order by its unique identifier.
   *
   * @param orderId - The unique identifier of the order.
   * @returns An ApiResponse containing the order data or an error message.
   */
  async getOrder(orderId: string): Promise<ApiResponse<unknown>> {
    if (!orderId) {
      return { success: false, error: "orderId is required" };
    }
    return this.request("GET", \`/orders/\${orderId}\`);
  }

  /**
   * Creates a new order.
   *
   * @param payload - The order data to create.
   * @returns An ApiResponse containing the created order or an error message.
   */
  async createOrder(payload: Record<string, unknown>): Promise<ApiResponse<unknown>> {
    if (!payload) {
      return { success: false, error: "payload is required" };
    }
    return this.request("POST", "/orders", payload);
  }

  /**
   * Cancels an existing order.
   *
   * @param orderId - The unique identifier of the order to cancel.
   * @returns An ApiResponse indicating whether the cancellation succeeded.
   */
  async cancelOrder(orderId: string): Promise<ApiResponse<unknown>> {
    if (!orderId) {
      return { success: false, error: "orderId is required" };
    }
    return this.request("POST", \`/orders/\${orderId}/cancel\`);
  }

  /**
   * Internal helper that performs the actual HTTP request, with automatic
   * retries on transient failures.
   *
   * @param method - The HTTP method to use.
   * @param path - The path to request, relative to the base URL.
   * @param body - Optional request body.
   * @returns An ApiResponse containing the response data or an error message.
   */
  private async request(method: string, path: string, body?: unknown): Promise<ApiResponse<unknown>> {
    let lastError: string | undefined;

    for (let attempt = 0; attempt < this.maxRetries; attempt++) {
      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), this.timeoutMs);

        const response = await fetch(\`\${this.baseUrl}\${path}\`, {
          method,
          headers: {
            "Content-Type": "application/json",
            Authorization: \`Bearer \${this.apiKey}\`,
          },
          body: body ? JSON.stringify(body) : undefined,
          signal: controller.signal,
        });

        clearTimeout(timeout);

        if (!response.ok) {
          lastError = \`Request failed with status \${response.status}\`;
          continue;
        }

        const data = await response.json();
        return { success: true, data, statusCode: response.status };
      } catch (error) {
        if (error instanceof Error) {
          lastError = error.message;
        } else {
          lastError = "Unknown error occurred";
        }
        console.error(\`Attempt \${attempt + 1} failed:\`, lastError);
      }
    }

    return { success: false, error: lastError ?? "Request failed after retries" };
  }
}
`;

const AI_USE_FETCH_HOOK_TSX = `import { useState, useEffect, useCallback } from "react";

/**
 * The state returned by the useFetchData hook.
 */
export interface FetchState<T> {
  data: T | null;
  isLoading: boolean;
  error: string | null;
}

/**
 * A custom hook for fetching data from an API endpoint.
 *
 * Handles loading state, error state, and automatic re-fetching when the
 * URL changes. Designed to be used with any JSON-returning endpoint.
 *
 * @param url - The URL to fetch data from.
 * @returns An object containing the fetched data, loading state, error
 * state, and a function to manually trigger a re-fetch.
 */
export function useFetchData<T>(url: string | null) {
  const [state, setState] = useState<FetchState<T>>({
    data: null,
    isLoading: false,
    error: null,
  });

  const fetchData = useCallback(async () => {
    if (!url) {
      return;
    }

    setState((prev) => ({ ...prev, isLoading: true, error: null }));

    try {
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error(\`Request failed with status \${response.status}\`);
      }

      const json = await response.json();
      setState({ data: json, isLoading: false, error: null });
    } catch (error) {
      const message = error instanceof Error ? error.message : "An unknown error occurred";
      console.error("useFetchData error:", message);
      setState({ data: null, isLoading: false, error: message });
    }
  }, [url]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return {
    data: state.data,
    isLoading: state.isLoading,
    error: state.error,
    refetch: fetchData,
  };
}

/**
 * A custom hook that debounces a value, useful for search inputs and
 * other scenarios where you want to delay processing until the user
 * has stopped typing.
 *
 * @param value - The value to debounce.
 * @param delayMs - The debounce delay in milliseconds.
 * @returns The debounced value.
 */
export function useDebouncedValue<T>(value: T, delayMs: number): T {
  const [debouncedValue, setDebouncedValue] = useState(value);

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedValue(value);
    }, delayMs);

    return () => {
      clearTimeout(timer);
    };
  }, [value, delayMs]);

  return debouncedValue;
}
`;

const AI_CACHE_UTIL_TS = `/**
 * A simple in-memory cache with time-to-live (TTL) expiration support.
 *
 * This utility is intended for caching short-lived data such as API
 * responses or computed values. It is not suitable for persistent storage.
 */

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

export class TTLCache<K, V> {
  private store: Map<K, CacheEntry<V>>;
  private defaultTtlMs: number;

  /**
   * Creates a new TTLCache instance.
   *
   * @param defaultTtlMs - The default time-to-live for cache entries, in milliseconds.
   */
  constructor(defaultTtlMs: number = 60_000) {
    this.store = new Map();
    this.defaultTtlMs = defaultTtlMs;
  }

  /**
   * Retrieves a value from the cache, if present and not expired.
   *
   * @param key - The key to look up.
   * @returns The cached value, or undefined if not found or expired.
   */
  get(key: K): V | undefined {
    const entry = this.store.get(key);

    if (!entry) {
      return undefined;
    }

    if (Date.now() > entry.expiresAt) {
      this.store.delete(key);
      return undefined;
    }

    return entry.value;
  }

  /**
   * Stores a value in the cache with an optional custom TTL.
   *
   * @param key - The key to store the value under.
   * @param value - The value to store.
   * @param ttlMs - Optional custom TTL, in milliseconds. Defaults to the cache's default TTL.
   */
  set(key: K, value: V, ttlMs?: number): void {
    const ttl = ttlMs ?? this.defaultTtlMs;
    this.store.set(key, { value, expiresAt: Date.now() + ttl });
  }

  /**
   * Checks whether a key exists in the cache and is not expired.
   *
   * @param key - The key to check.
   * @returns True if the key exists and is not expired, false otherwise.
   */
  has(key: K): boolean {
    return this.get(key) !== undefined;
  }

  /**
   * Removes a key from the cache.
   *
   * @param key - The key to remove.
   */
  delete(key: K): void {
    this.store.delete(key);
  }

  /**
   * Removes all entries from the cache.
   */
  clear(): void {
    this.store.clear();
  }

  /**
   * Removes all expired entries from the cache. Useful for periodic
   * cleanup to prevent unbounded memory growth.
   *
   * @returns The number of entries that were removed.
   */
  pruneExpired(): number {
    const now = Date.now();
    let removedCount = 0;

    for (const [key, entry] of this.store.entries()) {
      if (now > entry.expiresAt) {
        this.store.delete(key);
        removedCount++;
      }
    }

    return removedCount;
  }
}
`;

const AI_ETL_PIPELINE_TS = `/**
 * Utilities for transforming raw customer records exported from the legacy
 * CRM system into the normalized format expected by the new data warehouse.
 */

export interface RawCustomerRecord {
  cust_id: string;
  full_name: string;
  email_addr: string;
  signup_dt: string;
  acct_status: string;
  total_spend?: string;
}

export interface NormalizedCustomerRecord {
  customerId: string;
  firstName: string;
  lastName: string;
  email: string;
  signupDate: Date;
  isActive: boolean;
  totalSpendCents: number;
}

/**
 * Splits a full name into first and last name components.
 *
 * @param fullName - The full name to split.
 * @returns An object containing the first and last name.
 */
function splitFullName(fullName: string): { firstName: string; lastName: string } {
  if (!fullName || typeof fullName !== "string") {
    return { firstName: "", lastName: "" };
  }

  const parts = fullName.trim().split(/\\s+/);

  if (parts.length === 1) {
    return { firstName: parts[0], lastName: "" };
  }

  const lastName = parts[parts.length - 1];
  const firstName = parts.slice(0, -1).join(" ");

  return { firstName, lastName };
}

/**
 * Converts a dollar-denominated string amount into integer cents.
 *
 * @param amount - The dollar amount as a string (e.g. "1234.56").
 * @returns The equivalent amount in integer cents.
 */
function dollarsToCents(amount: string | undefined): number {
  if (!amount) {
    return 0;
  }

  const parsed = parseFloat(amount);

  if (Number.isNaN(parsed)) {
    return 0;
  }

  return Math.round(parsed * 100);
}

/**
 * Determines whether a customer account is currently active based on its
 * status string from the legacy CRM.
 *
 * @param status - The raw account status string.
 * @returns True if the account is active, false otherwise.
 */
function isAccountActive(status: string): boolean {
  if (!status) {
    return false;
  }

  const normalized = status.trim().toLowerCase();
  return normalized === "active" || normalized === "a" || normalized === "1";
}

/**
 * Transforms a single raw customer record from the legacy CRM into the
 * normalized format used by the data warehouse.
 *
 * @param raw - The raw customer record.
 * @returns The normalized customer record.
 */
export function normalizeCustomerRecord(raw: RawCustomerRecord): NormalizedCustomerRecord {
  const { firstName, lastName } = splitFullName(raw.full_name);

  return {
    customerId: raw.cust_id,
    firstName,
    lastName,
    email: raw.email_addr ? raw.email_addr.trim().toLowerCase() : "",
    signupDate: new Date(raw.signup_dt),
    isActive: isAccountActive(raw.acct_status),
    totalSpendCents: dollarsToCents(raw.total_spend),
  };
}

/**
 * Transforms a batch of raw customer records into normalized records,
 * skipping any records that fail to parse.
 *
 * @param rawRecords - An array of raw customer records.
 * @returns An array of successfully normalized customer records.
 */
export function normalizeCustomerBatch(rawRecords: RawCustomerRecord[]): NormalizedCustomerRecord[] {
  const results: NormalizedCustomerRecord[] = [];

  for (const raw of rawRecords) {
    try {
      const normalized = normalizeCustomerRecord(raw);
      results.push(normalized);
    } catch (error) {
      console.error(\`Failed to normalize record \${raw.cust_id}:\`, error);
    }
  }

  return results;
}
`;

export const BENCHMARK_SAMPLES: BenchmarkSample[] = [
  { id: "zod-util",            label: "human", language: "javascript", source: "node_modules/zod/v3/helpers/util.js",      content: ZOD_UTIL_JS },
  { id: "zod-parseutil",       label: "human", language: "javascript", source: "node_modules/zod/v3/helpers/parseUtil.js", content: ZOD_PARSEUTIL_JS },
  { id: "zod-zoderror",        label: "human", language: "javascript", source: "node_modules/zod/v3/ZodError.js",          content: ZOD_ZODERROR_JS },
  { id: "dompurify-utils",     label: "human", language: "typescript", source: "node_modules/dompurify/src/utils.ts",      content: DOMPURIFY_UTILS_TS },
  { id: "entities-escape",     label: "human", language: "typescript", source: "node_modules/entities/src/escape.ts",      content: ENTITIES_ESCAPE_TS },

  { id: "ai-validation-svc",   label: "ai",    language: "typescript", source: "freshly generated by Claude for this benchmark", content: AI_VALIDATION_SERVICE_TS },
  { id: "ai-api-client",       label: "ai",    language: "typescript", source: "freshly generated by Claude for this benchmark", content: AI_API_CLIENT_TS },
  { id: "ai-use-fetch-hook",   label: "ai",    language: "typescript", source: "freshly generated by Claude for this benchmark", content: AI_USE_FETCH_HOOK_TSX },
  { id: "ai-cache-util",       label: "ai",    language: "typescript", source: "freshly generated by Claude for this benchmark", content: AI_CACHE_UTIL_TS },
  { id: "ai-etl-pipeline",     label: "ai",    language: "typescript", source: "freshly generated by Claude for this benchmark", content: AI_ETL_PIPELINE_TS },
];
