/**
 * AI Model Attribution Engine v2
 *
 * Architecture: evidence-weighted Bayesian scoring
 *
 *   score(model) = Σ w(pattern_i) × match(pattern_i, content) × lang_boost(model, lang)
 *
 * Each model has positive patterns (evidence FOR) and negative patterns
 * (evidence AGAINST). Negative patterns reduce the model's total score.
 *
 * Human signals accumulate independently and suppress all AI scores.
 *
 * Final confidence is normalized against the full posterior distribution,
 * not a simple softmax — models compete for the same evidence pool.
 */

export type AIModel =
  | "github-copilot"
  | "chatgpt"
  | "gemini"
  | "claude"
  | "codewhisperer"
  | "cursor"
  | "tabnine"
  | "human"
  | "unknown";

export interface AttributionResult {
  model:      AIModel;
  confidence: number;               // 0–1, normalized posterior
  signals:    string[];             // human-readable evidence list
  breakdown:  Record<AIModel, number>;
  humanEvidence: number;            // 0–1.5, raw (un-normalized) human-signal strength
}

// ── Pattern definitions ────────────────────────────────────────────────────────

interface Pattern {
  re:     RegExp;
  weight: number;    // contribution when matched
  note:   string;    // shown in signals list
}

interface ModelDef {
  model:    AIModel;
  prior:    number;       // base probability (language-agnostic)
  positive: Pattern[];    // evidence FOR this model
  negative: Pattern[];    // evidence AGAINST (reduces score)
  langBoost: Partial<Record<string, number>>; // language multipliers
}

const MODELS: ModelDef[] = [
  // ─── GitHub Copilot ───────────────────────────────────────────────────────
  {
    model: "github-copilot",
    prior: 0.30,  // most popular tool, higher base rate
    langBoost: { typescript:1.5, javascript:1.5, python:1.0, golang:0.9 },
    positive: [
      // Copilot leaves trailing "// comment" on closing braces as context hints
      { re: /\)\s*\{\s*\/\/\s*[A-Za-z]\w{3,}/, weight: 0.20, note: "Trailing closing-brace comment (Copilot inline hint)" },
      // @ts-ignore / @ts-expect-error injected by Copilot when types fail
      { re: /\/\/\s*@ts-(?:ignore|expect-error)\b/, weight: 0.25, note: "@ts-ignore generated by Copilot to suppress its own type errors" },
      // Copilot-generated JSDoc with @param {Type} name - The ... article pattern
      { re: /\*\s*@param\s+\{[A-Za-z<>[\]|, ]+\}\s+\w+\s*[-—]\s*(?:The|A|An)\s+\w+/i, weight: 0.20, note: "JSDoc @param with 'The/A/An' article (Copilot docstring style)" },
      // Copilot tends to add prop comments on TypeScript interfaces
      { re: /:\s*(?:string|number|boolean|React\.ReactNode)\s*;?\s*\/\/\s*\w{3,}/, weight: 0.20, note: "Inline property comment on interface (Copilot TS pattern)" },
      // Copilot generates TODO with "implement" / "add error handling" etc.
      { re: /\/\/\s*TODO:\s*(?:implement|add error handling|handle edge case|add validation|improve)/i, weight: 0.15, note: "Copilot-style actionable TODO comment" },
      // Copilot React: function with displayName set
      { re: /\.\s*displayName\s*=\s*["'][A-Z]\w+["']/, weight: 0.15, note: "displayName assignment (Copilot React pattern)" },
      // Copilot generates // NOTE: in TypeScript/JS
      { re: /\/\/\s*NOTE:\s+[A-Z]/, weight: 0.10, note: "NOTE: comment prefix (Copilot inline note style)" },
    ],
    negative: [
      // Copilot rarely generates step-by-step numbered comments
      { re: /(?:\/\/|#)\s*Step\s+\d+[:.]/i, weight: 0.40, note: "Step-by-step comments (ChatGPT pattern, not Copilot)" },
      // Copilot rarely generates Python Google docstrings
      { re: /(?:Args|Returns|Raises):\s*\n\s+\w[^:\n]+:/, weight: 0.30, note: "Google docstring (Gemini/ChatGPT, not Copilot)" },
    ],
  },

  // ─── ChatGPT ──────────────────────────────────────────────────────────────
  {
    model: "chatgpt",
    prior: 0.25,
    langBoost: { python:1.4, javascript:1.1, typescript:1.0 },
    positive: [
      // ChatGPT signature: verbose Python docstrings with Args/Returns/Raises sections
      { re: /(?:"""|\'\'\')[\s\S]{80,600}?(?:Args|Parameters|Returns|Raises|Yields):/, weight: 0.35, note: "Verbose docstring with Args/Returns sections (ChatGPT Python style)" },
      // "# Step 1:" sequential numbered comments — very ChatGPT
      { re: /(?:\/\/|#)\s*Step\s+[1-9]\d*[:.]/i, weight: 0.30, note: "Numbered step comments (ChatGPT explanation style)" },
      // "# This implementation..." / "# This function..." sentence preamble
      { re: /(?:^|\n)\s*#\s*This (?:implementation|function|class|approach|solution)\b/im, weight: 0.25, note: "'This implementation' comment (ChatGPT narrative style)" },
      // "# Note: This is a..." explanatory parenthetical blocks
      { re: /(?:^|\n)\s*(?:#|\/\/)\s*Note:\s+This\b/im, weight: 0.20, note: "'Note: This' comment block (ChatGPT explanation style)" },
      // Example: / Usage: with >>> REPL examples
      { re: /(?:Example(?:s)?|Usage):\s*\n\s*>>>/i, weight: 0.20, note: "REPL example in docstring (ChatGPT pedagogical style)" },
      // if __name__ == "__main__": with print() demo
      { re: /__name__\s*==\s*['"]__main__['"]/,   weight: 0.15, note: "__main__ guard with demo code (ChatGPT complete-example pattern)" },
      // Verbose inline explanation of obvious operations
      { re: /(?:\/\/|#)\s*(?:First|Then|Finally|Next|Now|Here)\s*(?:,|we)\s+\w/i, weight: 0.15, note: "Narrative transition comment (ChatGPT step-by-step explanation)" },
      // "# Helper function to..."
      { re: /(?:\/\/|#)\s*Helper\s+(?:function|method|class)\s+to\s+\w/i, weight: 0.10, note: "'Helper function to' comment label (ChatGPT pattern)" },
    ],
    negative: [
      // ChatGPT rarely uses TS-specific decorators
      { re: /@Injectable\(\)|@Component\(\)|@Module\(\)/, weight: 0.25, note: "Framework decorator (CodeWhisperer/Copilot, not ChatGPT)" },
    ],
  },

  // ─── Gemini (Google DeepMind) ─────────────────────────────────────────────
  {
    model: "gemini",
    prior: 0.15,
    langBoost: { python:1.5, java:1.3, kotlin:1.3, typescript:0.9 },
    positive: [
      // Gemini / Google style: strict Google docstring format with type annotations
      { re: /(?:Args|Returns|Raises|Yields|Attributes):\s*\n(?:\s{4,}\w[^:\n]+:[^\n]+\n){2,}/, weight: 0.35, note: "Google-style docstring with indented sections (Gemini signature)" },
      // Gemini generates type hints on ALL function parameters (Python)
      { re: /def\s+\w+\([^)]*:\s*(?:str|int|float|bool|Optional|Union|List|Dict|Tuple|Any|Callable|Type)\b/, weight: 0.25, note: "Fully typed function signature (Gemini Python pattern)" },
      // `from typing import` with 3+ types
      { re: /from\s+typing\s+import\s+(?:\w+,\s*){2,}\w+/, weight: 0.20, note: "Batch typing import (Gemini Python style)" },
      // @dataclass with field() defaults
      { re: /@dataclass(?:\s*\(.*\))?\s*\nclass\s+\w+/, weight: 0.20, note: "@dataclass usage (Gemini preference for data classes)" },
      // Pydantic BaseModel usage
      { re: /class\s+\w+\s*\(\s*BaseModel\s*\)/, weight: 0.15, note: "Pydantic BaseModel (Gemini API patterns)" },
      // Google Cloud SDK imports
      { re: /from\s+google\.\w+\s+import\b|import\s+google\.\w+/, weight: 0.15, note: "Google Cloud SDK import (Gemini training data bias)" },
      // Protocol Buffers or gRPC
      { re: /import\s+grpc\b|pb2\b|\.proto\b/, weight: 0.15, note: "gRPC/Protobuf usage (Google ecosystem)" },
    ],
    negative: [
      { re: /import\s+boto3\b|from\s+boto3/, weight: 0.40, note: "boto3 import (AWS/CodeWhisperer, not Gemini)" },
      { re: /(?:^|\n)\s*#\s*Step\s+\d+:/im,  weight: 0.20, note: "Step comments (ChatGPT style)" },
    ],
  },

  // ─── Claude (Anthropic) ───────────────────────────────────────────────────
  {
    model: "claude",
    prior: 0.12,
    langBoost: { typescript:1.3, python:1.1, rust:1.2, markdown:1.5 },
    positive: [
      // Claude's distinctive section separator style: # ── Name ──────
      { re: /(?:^|\n)\s*(?:#|\/\/)\s*─{3,}\s*[\w\s]+─{2,}/m, weight: 0.35, note: "Section separator with em-dashes (Claude style marker)" },
      // Claude uses "We/Let's/Here we" conversational style in comments
      { re: /(?:^|\n)\s*(?:#|\/\/)\s*(?:We|Let's|Here we|We need to|We can)\s+\w/im, weight: 0.25, note: "Conversational 'We/Let's' comment (Claude narrative style)" },
      // Claude adds "// ── Type definitions ──" before type blocks
      { re: /(?:\/\/|#)\s*─{2,}\s*(?:Type|Interface|Types|Interfaces|Constants|Helpers?|Utils?)\s+─{2,}/i, weight: 0.25, note: "Labelled code section with dashes (Claude organisation pattern)" },
      // Claude uses "// IMPORTANT:" / "// NOTE:" with capital start
      { re: /(?:\/\/|#)\s*(?:IMPORTANT|NOTE|WARNING):\s+[A-Z]/, weight: 0.20, note: "Capitalised NOTE/IMPORTANT prefix (Claude emphasis style)" },
      // Claude tends to write longer inline explanations on non-obvious lines
      { re: /(?:\/\/|#)\s*\w.{30,100}$(?=\n)/m, weight: 0.15, note: "Long explanatory inline comment (Claude verbosity)" },
      // Claude uses `satisfies` operator in TypeScript
      { re: /\bsatisfies\b/, weight: 0.15, note: "'satisfies' operator (Claude modern TypeScript preference)" },
    ],
    negative: [
      { re: /import\s+boto3\b/,                weight: 0.40, note: "boto3 import (AWS/CodeWhisperer)" },
      { re: /(?:^|\n)\s*#\s*Step\s+\d+:/im,   weight: 0.20, note: "Step comments (ChatGPT style)" },
    ],
  },

  // ─── AWS CodeWhisperer ────────────────────────────────────────────────────
  {
    model: "codewhisperer",
    prior: 0.08,
    langBoost: { python:1.6, java:1.4, javascript:1.0 },
    positive: [
      // boto3 is the clearest single signal
      { re: /import\s+boto3\b|from\s+boto3\s+import/, weight: 0.40, note: "boto3 import (AWS SDK — strong CodeWhisperer signal)" },
      // AWS-specific exception classes
      { re: /except\s+(?:ClientError|BotoCoreError|NoCredentialsError|EndpointResolutionError)\b/, weight: 0.30, note: "AWS botocore exception (CodeWhisperer error handling)" },
      // ARN patterns
      { re: /arn:aws:[a-z0-9]+:[a-z0-9-]*:\d+:/, weight: 0.25, note: "AWS ARN string (CodeWhisperer AWS pattern)" },
      // Lambda handler signature
      { re: /def\s+(?:handler|lambda_handler)\s*\(\s*event\s*,\s*context\s*\)/, weight: 0.25, note: "Lambda handler signature (CodeWhisperer AWS pattern)" },
      // S3/DynamoDB/SQS method chains
      { re: /boto3\.(?:client|resource)\s*\(\s*["'](?:s3|dynamodb|sqs|sns|lambda|iam|ec2)["']/, weight: 0.20, note: "boto3 service client (CodeWhisperer AWS service pattern)" },
      // AWS SDK for JavaScript/TypeScript (v3)
      { re: /@aws-sdk\/client-\w+/, weight: 0.20, note: "@aws-sdk import (CodeWhisperer JavaScript/TypeScript)" },
    ],
    negative: [
      { re: /from\s+google\.\w+\s+import\b/, weight: 0.30, note: "Google Cloud import (Gemini, not CodeWhisperer)" },
    ],
  },

  // ─── Cursor (AI-first IDE) ────────────────────────────────────────────────
  // Cursor uses a mix of Claude and GPT-4 under the hood but produces
  // its own characteristic output patterns.
  {
    model: "cursor",
    prior: 0.08,
    langBoost: { typescript:1.4, javascript:1.3, python:1.0 },
    positive: [
      // Cursor generates // [AI]: prefix on generated sections
      { re: /\/\/\s*\[(?:AI|Cursor|Generated)\]:/i, weight: 0.50, note: "[AI] comment prefix (Cursor explicit labelling)" },
      // Cursor adds file-level context comments at the top
      { re: /(?:^|\n)\/\/\s*(?:File:|Path:|Context:|Purpose:)\s+\w/im, weight: 0.30, note: "File-level context comment (Cursor file-aware generation)" },
      // Cursor produces "// @cursor-generated" markers occasionally
      { re: /@cursor-generated|@ai-generated/i, weight: 0.40, note: "Cursor-generated annotation" },
      // Cursor tends to use zod for all validation
      { re: /(?:import|require).*\bzod\b|z\.(?:object|string|number|array|enum)\b/, weight: 0.20, note: "Zod schema (Cursor validation preference)" },
      // Cursor uses trpc patterns
      { re: /\.procedure\.|createTRPCRouter|publicProcedure|protectedProcedure/, weight: 0.20, note: "tRPC procedure (Cursor full-stack pattern)" },
    ],
    negative: [],
  },

  // ─── Tabnine ──────────────────────────────────────────────────────────────
  // Tabnine is a completion engine — minimal comments, short functions.
  // Hard to distinguish from human code; we look for its specific completion artifacts.
  {
    model: "tabnine",
    prior: 0.05,
    langBoost: { javascript:1.2, python:1.1 },
    positive: [
      // Tabnine completes single-expression returns (chain completions)
      { re: /(?:return|=>)\s+\w+\.\w+\(\w*\)\s*[;,]/, weight: 0.20, note: "Single-expression method chain return (Tabnine completion)" },
      // Magic timeout constants that Tabnine commonly auto-fills
      { re: /(?:timeout|delay|interval|retryDelay)\s*[:=]\s*(?:1000|3000|5000|10000|30000|60000)\b/, weight: 0.15, note: "Common timeout magic number (Tabnine auto-fill)" },
      // Very low comment density combined with short functions (Tabnine's style)
      // (handled structurally, not by pattern)
    ],
    negative: [
      // Tabnine almost never generates verbose docstrings
      { re: /\/\*\*[\s\S]{100,}?\*\//,          weight: 0.30, note: "Long JSDoc block (Copilot/ChatGPT, not Tabnine)" },
      { re: /(?:Args|Returns):\s*\n\s+\w[^:\n]+:/, weight: 0.30, note: "Google docstring (Gemini, not Tabnine)" },
    ],
  },
];

// ── Human signals ─────────────────────────────────────────────────────────────
// These reduce confidence in ALL AI models proportionally.

interface HumanSignal { re: RegExp; weight: number; note: string }

const HUMAN_SIGNALS: HumanSignal[] = [
  // Typos and autocorrect misses
  { re: /\b(?:teh|dont|cant|wont|shouldnt|wouldnt|couldnt|thier|recieve|occured)\b/i, weight: 0.20, note: "Typo (human writing error)" },
  // Emotional / informal comments
  { re: /\b(?:wtf|lol|omg|damn|crap|ugh|ffs|smh|yolo)\b/i, weight: 0.20, note: "Informal expression (human emotional marker)" },
  // First-person uncertainty
  { re: /(?:I think|I'm not sure|not sure why|idk|tbh|honestly|lmao)\b/i, weight: 0.15, note: "First-person uncertainty (human authorship signal)" },
  // Dated comments (version tracking by hand)
  { re: /(?:\/\/|#)\s*\d{4}-\d{2}-\d{2}/, weight: 0.15, note: "Date-stamped comment (human version tracking)" },
  // Commented-out old code
  { re: /(?:\/\/|#)\s*(?:old|previous|legacy|deprecated|broken|fix)\s*:?\s*\w+\s*\(/i, weight: 0.20, note: "Commented-out old function (human experimentation)" },
  // Personal attribution
  { re: /(?:\/\/|#)\s*(?:@author|written by|added by|created by)\s+[A-Z][a-z]/i, weight: 0.25, note: "Personal attribution comment (human authorship)" },
  // FIXME / HACK with personal context
  { re: /(?:FIXME|HACK|XXX|BUG)\s*(?:\([^)]+\))?:\s*\w/, weight: 0.15, note: "Informal FIXME/HACK comment (human code debt)" },
  // Inconsistent whitespace (tab/space mixing)
  { re: /\t   |\t  /, weight: 0.10, note: "Inconsistent indentation (human editor mix)" },
  // Ad-hoc debug print that was left in
  { re: /console\.debug\s*\(|pprint\s*\(|print\s*\(["']DEBUG/i, weight: 0.15, note: "Debug print statement (human debugging artifact)" },
];

// ── Attribution algorithm ─────────────────────────────────────────────────────

export function attributeCode(content: string, language: string): AttributionResult {
  if (!content || content.trim().length < 50) {
    return { model:"unknown", confidence:0, signals:[], breakdown: emptyBreakdown(), humanEvidence: 0 };
  }

  const scores: Record<AIModel, number> = emptyBreakdown();
  const evidenceLog: string[] = [];

  // Score each AI model
  for (const def of MODELS) {
    let raw = def.prior;

    // Positive evidence accumulation
    for (const p of def.positive) {
      if (p.re.test(content)) {
        raw += p.weight;
        if (raw - def.prior > 0.1 && !evidenceLog.includes(p.note)) {
          evidenceLog.push(`[${def.model}] ${p.note}`);
        }
      }
    }

    // Negative evidence (penalise — scales down by the pattern's weight)
    for (const n of def.negative) {
      if (n.re.test(content)) raw *= (1 - n.weight);
    }

    // Language boost (multiply after accumulation)
    const boost = def.langBoost[language] ?? 1.0;
    scores[def.model] = Math.min(3.0, raw * boost);  // cap raw score at 3x prior
  }

  // Human signal accumulation
  let humanEvidence = 0;
  const humanNotes: string[] = [];
  for (const h of HUMAN_SIGNALS) {
    if (h.re.test(content)) {
      humanEvidence += h.weight;
      humanNotes.push(h.note);
    }
  }
  humanEvidence = Math.min(1.5, humanEvidence);
  scores.human = humanEvidence;

  // Human evidence suppresses all AI scores proportionally
  if (humanEvidence > 0) {
    const suppression = 1 - Math.min(0.75, humanEvidence * 0.5);
    for (const model of MODELS) {
      scores[model.model] *= suppression;
    }
  }

  // Normalise to a proper posterior distribution
  const total = Object.values(scores).reduce((a, b) => a + b, 0) || 1;
  const posterior: Record<AIModel, number> = {} as Record<AIModel, number>;
  for (const k of Object.keys(scores) as AIModel[]) {
    posterior[k] = scores[k] / total;
  }

  // Winner
  const entries = Object.entries(posterior) as [AIModel, number][];
  entries.sort(([, a], [, b]) => b - a);
  const [topModel, topConf] = entries[0];
  const [secondModel, secondConf] = entries[1] ?? ["unknown", 0];

  // Confidence requires winning by a margin (suppress "unknown" wins with low evidence)
  const margin = topConf - secondConf;
  const model: AIModel =
    topModel === "unknown" || topConf < 0.20 ? "unknown" :
    topModel === "human"   || margin < 0.05  ? (humanEvidence > 0.3 ? "human" : "unknown") :
    topModel;

  const confidence = Math.min(1, topConf * (1 + margin));  // boost by margin

  // Build human-readable signals for the UI
  const signals: string[] = [];
  for (const [m, p] of entries.slice(0, 3)) {
    if (p < 0.10) continue;
    const pct = Math.round(p * 100);
    if (m === "github-copilot") signals.push(`GitHub Copilot: ${pct}% — inline comment style and TypeScript patterns`);
    if (m === "chatgpt")        signals.push(`ChatGPT: ${pct}% — verbose docstrings, step-by-step comments`);
    if (m === "gemini")         signals.push(`Gemini: ${pct}% — Google-style docstrings, typing module usage`);
    if (m === "claude")         signals.push(`Claude: ${pct}% — section separators, conversational comments`);
    if (m === "codewhisperer")  signals.push(`CodeWhisperer: ${pct}% — boto3/AWS SDK patterns`);
    if (m === "cursor")         signals.push(`Cursor: ${pct}% — [AI] labels, file-context comments`);
    if (m === "tabnine")        signals.push(`Tabnine: ${pct}% — minimal comments, short completions`);
    if (m === "human")          signals.push(`Human: ${pct}% — ${humanNotes[0] ?? "personal style markers"}`);
  }
  if (model === "unknown") signals.push("Attribution unclear — mixed or insufficient signals");

  // Add top evidence from evidence log
  for (const e of evidenceLog.slice(0, 2)) signals.push(e);

  return { model, confidence, signals, breakdown: posterior, humanEvidence };
}

function emptyBreakdown(): Record<AIModel, number> {
  return { "github-copilot":0, chatgpt:0, gemini:0, claude:0, codewhisperer:0, cursor:0, tabnine:0, human:0, unknown:0 };
}

// ── Model display metadata ────────────────────────────────────────────────────

export const MODEL_META: Record<AIModel, { label: string; color: string; bg: string; icon: string }> = {
  "github-copilot": { label:"GitHub Copilot",    color:"#6d28d9", bg:"#ede9fe", icon:"🤖" },
  chatgpt:          { label:"ChatGPT",            color:"#10a37f", bg:"#d1fae5", icon:"💬" },
  gemini:           { label:"Gemini",             color:"#1a73e8", bg:"#dbeafe", icon:"✨" },
  claude:           { label:"Claude",             color:"#d97706", bg:"#fef3c7", icon:"🔮" },
  codewhisperer:    { label:"CodeWhisperer",      color:"#ff9900", bg:"#fff7ed", icon:"☁️" },
  cursor:           { label:"Cursor AI",          color:"#0ea5e9", bg:"#e0f2fe", icon:"⚡" },
  tabnine:          { label:"Tabnine",            color:"#6366f1", bg:"#eef2ff", icon:"🔷" },
  human:            { label:"Human-written",      color:"#15803d", bg:"#f0fdf4", icon:"👤" },
  unknown:          { label:"Unknown / Mixed",    color:"#6b7280", bg:"#f9fafb", icon:"❓" },
};
