/**
 * False-positive benchmark baseline -- every currently-accepted (file, id,
 * line) security finding produced by scanning this project's own src/ tree
 * (the corpus fpBenchmarkCorpus.benchmark.test.ts scans), each with a real,
 * individually-verified reason it's not a genuine vulnerability. See
 * src/lib/fpBenchmark.ts for the diff mechanism this feeds, and
 * fpBenchmarkCorpus.benchmark.test.ts for how it's consumed.
 *
 * Seeded from a full hand-triage of the 149 findings this corpus
 * produced after fixing the AI_SIGNAL_IDS gap (scanner.ts) -- every entry
 * below was read in source, not bulk-accepted. Six root-cause classes
 * (catalog/label UI text self-matching detector keywords, a detector's own
 * pattern-definition regex self-matching its own vocabulary, demo/seed
 * fixture content never executed, an array-index type-inference gap in
 * hallucinated-method-call, a Supabase realtime filter colliding with the
 * word "filter", and Next.js route handlers parsing their own inbound
 * request URL) explain the overwhelming majority; a handful of individually
 * bespoke cases (weak-cors, verbose-error, three dangerouslySetInnerHTML
 * sites) were each read and reasoned about on their own.
 *
 * A NEW finding not in this list fails fpBenchmarkCorpus.benchmark.test.ts
 * -- either fix the underlying code/detector, or add an entry here with a
 * real reason. A STALE entry (no longer produced live) also fails the test
 * -- remove it once confirmed fixed, or re-verify and update its lineHash if
 * the surrounding line changed.
 */

import type { FpBaselineEntry } from "./fpBenchmark";

export const FP_BASELINE: FpBaselineEntry[] = [
  { file: "src/lib/seedFileSamples.ts", id: "command-injection", lineHash: "e5aa10162c73", line: 450, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/pr/[id]/page.tsx", id: "eval-exec", lineHash: "007720b07a0e", line: 32, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/risk-register/page.tsx", id: "eval-exec", lineHash: "68f4c45370fe", line: 236, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/violations/page.tsx", id: "eval-exec", lineHash: "843a9a6c16e1", line: 28, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/violations/page.tsx", id: "eval-exec", lineHash: "6b0a735908ba", line: 297, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/components/AIIntelligencePanel.tsx", id: "eval-exec", lineHash: "f680283ec27b", line: 40, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "e6934e5b9b89", line: 72, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "0d2804f64bb9", line: 78, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "4b71e6dc0829", line: 83, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "580c70b4f318", line: 482, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "2853b81a86ea", line: 483, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "b57628b649a2", line: 498, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/compliance.ts", id: "eval-exec", lineHash: "572897493573", line: 137, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/sarif.ts", id: "eval-exec", lineHash: "a86b069f7612", line: 35, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "7bc2608ba37f", line: 241, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "5fb22922bd11", line: 242, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "49749f1929a2", line: 244, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "f1686fe6bf42", line: 247, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "16bda5d7c77c", line: 249, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "9adff12bee91", line: 254, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seedFileSamples.ts", id: "eval-exec", lineHash: "992728c5f7fc", line: 598, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/threatCatalog.ts", id: "eval-exec", lineHash: "433c06deac29", line: 85, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "54f6f58bc7bd", line: 58, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "9c3804adbe8b", line: 59, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "b0125e05afb6", line: 60, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/analytics/page.tsx", id: "hallucinated-method-call", lineHash: "60c50182dc7a", line: 23, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/analytics/page.tsx", id: "hallucinated-method-call", lineHash: "df5ef068f015", line: 24, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/api/dependencies/graph/route.ts", id: "hallucinated-method-call", lineHash: "1e8ae6ea16c0", line: 73, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/api/dependencies/graph/route.ts", id: "hallucinated-method-call", lineHash: "e95f047b7692", line: 74, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/api/dependencies/graph/route.ts", id: "hallucinated-method-call", lineHash: "ffeb8d445f52", line: 96, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/api/integrations/health/route.ts", id: "hallucinated-method-call", lineHash: "972f72617f8c", line: 63, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/api/scan-worker/route.ts", id: "hallucinated-method-call", lineHash: "5ffc6224cb07", line: 273, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/posture/page.tsx", id: "hallucinated-method-call", lineHash: "c525d6c04f81", line: 140, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/reports/page.tsx", id: "hallucinated-method-call", lineHash: "87af1abcc8f3", line: 1495, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/risk-register/page.tsx", id: "hallucinated-method-call", lineHash: "d3eaa21a799e", line: 1076, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/shadow-ai/page.tsx", id: "hallucinated-method-call", lineHash: "e03ef89e0721", line: 453, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/app/threat-intel/page.tsx", id: "hallucinated-method-call", lineHash: "cf9a7833e357", line: 305, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/aiAttribution.ts", id: "hallucinated-method-call", lineHash: "765ed85fe523", line: 348, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/aiAttributionBenchmark.fixtures.ts", id: "hallucinated-method-call", lineHash: "33df73ba0453", line: 475, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "692e57026f43", line: 155, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "06824cfe50f6", line: 209, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "192a4d1a7947", line: 336, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "54b44f9cfca4", line: 389, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "69d2d5dbb6aa", line: 390, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "50f14dd4ca4a", line: 407, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "7394aecd195d", line: 409, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "7f08220f5c8a", line: 432, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "984244ac78ba", line: 438, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "e3c5d8ca020a", line: 463, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/ast.ts", id: "hallucinated-method-call", lineHash: "e3c5d8ca020a-1", line: 471, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/callGraph.ts", id: "hallucinated-method-call", lineHash: "b0553f086615", line: 103, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/callGraph.ts", id: "hallucinated-method-call", lineHash: "fa31f3f881e4", line: 179, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/callGraph.ts", id: "hallucinated-method-call", lineHash: "7cc70b1059f0", line: 181, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/callGraph.ts", id: "hallucinated-method-call", lineHash: "99b46c0c960a", line: 277, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/callGraph.ts", id: "hallucinated-method-call", lineHash: "bf9be0d84e6f", line: 318, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/depAnalysis.ts", id: "hallucinated-method-call", lineHash: "fc8ea689b13f", line: 191, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/depAnalysis.ts", id: "hallucinated-method-call", lineHash: "f0482c3808a0", line: 194, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/depAnalysis.ts", id: "hallucinated-method-call", lineHash: "65951948bf94", line: 251, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/depAnalysis.ts", id: "hallucinated-method-call", lineHash: "024b2240f4d9", line: 348, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "b079ac22f7da", line: 209, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "925d63e4359e", line: 210, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "8088168fbcdd", line: 215, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "74c988903cc3", line: 226, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "20487928ae03", line: 233, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "5acad77bd43c", line: 289, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "79c1bdc5e9ae", line: 301, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/dependencyScan.ts", id: "hallucinated-method-call", lineHash: "83787e1dd9c6", line: 304, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/gitProvenance.ts", id: "hallucinated-method-call", lineHash: "42237015c486", line: 95, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/gitProvenance.ts", id: "hallucinated-method-call", lineHash: "84b25ec75695", line: 96, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/gitProvenance.ts", id: "hallucinated-method-call", lineHash: "393829406812", line: 97, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/gitProvenance.ts", id: "hallucinated-method-call", lineHash: "4b9ade3e113f", line: 98, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/gitProvenance.ts", id: "hallucinated-method-call", lineHash: "f07da6dc7ca3", line: 99, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "71cd81c09877", line: 441, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "acf2145431cf", line: 442, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "7e372dd877ac", line: 445, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "7e372dd877ac-1", line: 449, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "2cb2c8585c2d", line: 480, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "259e44705908", line: 481, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "b9a11d5fbde0", line: 524, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "367e93909cb2", line: 622, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "f218faddb798", line: 623, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "789aa3b46679", line: 1117, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "8d6e027b3795", line: 1295, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site (m[1].matchAll(), added by the Go OWASP hardening phase's SQL-injection Sprintf detector)." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "09b17b4a48e8", line: 1358, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "8d6e027b3795-1", line: 1434, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site (m[1].matchAll(), added by the Go OWASP hardening phase's command-injection detector)." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "09b17b4a48e8-1", line: 1562, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site (joinMatch[1].matchAll(), added by the Go OWASP hardening phase's path-traversal detector)." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "09b17b4a48e8-2", line: 1698, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site (joinMatch[1].matchAll(), added by the C# OWASP hardening phase's path-traversal detector -- textually identical to the Go sibling's own already-baselined occurrence)." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "22a5d5b840fa", line: 1646, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "77d5c1a59f87", line: 2657, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "05d424ef145b", line: 2658, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "96aef14cc47b", line: 2850, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "a02964b56a4d", line: 3461, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/seedFileSamples.ts", id: "hallucinated-method-call", lineHash: "4dda8618a323", line: 422, severity: "medium",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/seedFileSamples.ts", id: "hallucinated-method-call", lineHash: "5d56f0af00b4", line: 453, severity: "medium",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/seedFileSamples.ts", id: "hallucinated-method-call", lineHash: "c214a36398b3", line: 499, severity: "medium",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/components/NewScanPanel.tsx", id: "hardcoded-secret", lineHash: "03a1a70cc450", line: 55, severity: "high",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/seedFileSamples.ts", id: "insecure-deserialization", lineHash: "ea197b071a38", line: 422, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/pr/[id]/page.tsx", id: "insecure-randomness", lineHash: "a7c5a5fc3b90", line: 52, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "insecure-randomness", lineHash: "19b975d6ce0f", line: 115, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "jwt-none-alg", lineHash: "2c086b6c0303", line: 45, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/realtime.ts", id: "ldap-injection", lineHash: "fc10a9f0feed", line: 173, severity: "critical",
    reason: "This is a Supabase Postgres realtime channel filter string (`filter: `org_id=eq.${...}`), not an LDAP filter -- pure keyword collision on the word \"filter\"." },
  { file: "src/lib/licenseContamination.ts", id: "license-header-contamination", lineHash: "54f37ad57cd7", line: 106, severity: "medium",
    reason: "This is the license-detector's OWN pattern-definition string (a literal snippet of real MIT/BSD license text used to detect copied license headers elsewhere) -- self-matches its own regex." },
  { file: "src/lib/licenseContamination.ts", id: "license-header-contamination", lineHash: "27ae6dba759c", line: 110, severity: "medium",
    reason: "This is the license-detector's OWN pattern-definition string (a literal snippet of real MIT/BSD license text used to detect copied license headers elsewhere) -- self-matches its own regex." },
  { file: "src/components/NewScanPanel.tsx", id: "sql-injection", lineHash: "3123f0f4c285", line: 37, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "sql-injection", lineHash: "c381c60f5f1c", line: 44, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/seedFileSamples.ts", id: "sql-injection", lineHash: "d93a626aea03", line: 69, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/api/alerts/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 60, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/analytics/trends/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 37, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/audit/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 10, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/auth/2fa/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 117, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/compliance-config/route.ts", id: "ssrf", lineHash: "2342f6ba5dfd", line: 7, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/dashboard/route.ts", id: "ssrf", lineHash: "a06d87cb9567", line: 11, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/dependencies/graph/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 183, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/evidence/collect/route.ts", id: "ssrf", lineHash: "b8fab07a11fb", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 37, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/sarif/route.ts", id: "ssrf", lineHash: "88790235158d", line: 22, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/signed/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 25, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/github-app/manifest/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 20, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/incidents/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 12, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/report/history/route.ts", id: "ssrf", lineHash: "2993b049c663", line: 19, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/repos/route.ts", id: "ssrf", lineHash: "f24484f95a04", line: 32, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/retention/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 67, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/retention/route.ts", id: "ssrf", lineHash: "5ae001042f4e-1", line: 162, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/bulk/route.ts", id: "ssrf", lineHash: "420f90eb0480", line: 23, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/compare/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 20, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/[id]/route.ts", id: "ssrf", lineHash: "8526dad1cd65", line: 50, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/[id]/route.ts", id: "ssrf", lineHash: "8526dad1cd65-1", line: 79, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 60, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/route.ts", id: "ssrf", lineHash: "281991ffdc72", line: 109, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/search/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 43, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/secrets/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 33, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/sla/trend/route.ts", id: "ssrf", lineHash: "66d543b2e1a5", line: 22, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/storage/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 26, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/storage/route.ts", id: "ssrf", lineHash: "a06d87cb9567", line: 122, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/stripe/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 17, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/team/route.ts", id: "ssrf", lineHash: "24bfb15488af", line: 167, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/usage/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 38, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/violations/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 14, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 41, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "1644e9155920", line: 81, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "44ed02815ff5", line: 129, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "f24484f95a04", line: 41, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 168, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/lib/errors.ts", id: "verbose-error", lineHash: "2dffa306ce8c", line: 48, severity: "medium",
    reason: "This is safeError(), the app's own centralized safe-error-handling utility. err.stack is passed only to logger.error(...) (server-side structured logging) -- the client response (line 52-53) only ever receives { error: opts.code, message: opts.message, ref_id: refId }, a sanitized message with a correlation id. The detector flags proximity to \"stack\" without seeing that it never reaches the HTTP response." },
  { file: "src/app/api/docs/route.ts", id: "weak-cors", lineHash: "5ad176110a75", line: 6, severity: "medium",
    reason: "Public OpenAPI spec endpoint (GET-only, no auth/cookies/session data) -- wildcard CORS is intentional so external API tooling and documentation generators can fetch the spec cross-origin. No sensitive data is served here." },
  { file: "src/lib/seedFileSamples.ts", id: "weak-crypto", lineHash: "a6417ea270ec", line: 444, severity: "high",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/vulnCatalog.ts", id: "weak-crypto", lineHash: "ea4abd0ebbe6", line: 115, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/audit/page.tsx", id: "xss", lineHash: "75c80b8c460e", line: 85, severity: "critical",
    reason: "The `I` helper is defined but never invoked anywhere in this file (confirmed: no JSX usage, no call site) -- its dangerouslySetInnerHTML can never execute with any value at runtime. Effectively dead code; worth a future cleanup, but not a live XSS sink." },
  { file: "src/app/docs/page.tsx", id: "xss", lineHash: "824f2ab04e15", line: 20, severity: "critical",
    reason: "Static CSS string passed to dangerouslySetInnerHTML with zero interpolated variables (a plain template literal, no ${...} expressions) -- no dynamic content of any kind ever reaches this call." },
  { file: "src/app/trust-score/page.tsx", id: "xss", lineHash: "31dca680a91f", line: 149, severity: "critical",
    reason: "`org` (the only interpolated value not locally computed from `score`) is derived from `effectiveData?.repos?.[0]?.repo.split(\"/\")[0]` -- a GitHub org/user login segment, which GitHub itself restricts to alphanumerics and hyphens (no HTML metacharacters possible through this path). Impact is also bounded to self-XSS: document.write runs in a window.open() popup the acting user opened for their own org, not a sink reachable by any other user. Accepted with this specific caveat, not templated -- revisit if `org` is ever sourced from a less-constrained field." },
  { file: "src/lib/ast.ts", id: "xss", lineHash: "a5a8570f0472", line: 484, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
];
