/**
 * False-positive benchmark baseline -- every currently-accepted (file, id,
 * line) security finding produced by scanning this project's own src/ tree
 * (the corpus fpBenchmarkCorpus.benchmark.test.ts scans), each with a real,
 * individually-verified reason it's not a genuine vulnerability. See
 * src/lib/fpBenchmark.ts for the diff mechanism this feeds, and
 * fpBenchmarkCorpus.benchmark.test.ts for how it's consumed.
 *
 * Seeded from a full hand-triage of the 149 findings this corpus
 * produced after fixing the AI_SIGNAL_IDS gap (scanner.ts) -- every entry
 * below was read in source, not bulk-accepted. Six root-cause classes
 * (catalog/label UI text self-matching detector keywords, a detector's own
 * pattern-definition regex self-matching its own vocabulary, demo/seed
 * fixture content never executed, an array-index type-inference gap in
 * hallucinated-method-call, a Supabase realtime filter colliding with the
 * word "filter", and Next.js route handlers parsing their own inbound
 * request URL) explain the overwhelming majority; a handful of individually
 * bespoke cases (weak-cors, verbose-error, three dangerouslySetInnerHTML
 * sites) were each read and reasoned about on their own.
 *
 * A NEW finding not in this list fails fpBenchmarkCorpus.benchmark.test.ts
 * -- either fix the underlying code/detector, or add an entry here with a
 * real reason. A STALE entry (no longer produced live) also fails the test
 * -- remove it once confirmed fixed, or re-verify and update its lineHash if
 * the surrounding line changed.
 */

import type { FpBaselineEntry } from "./fpBenchmark";

export const FP_BASELINE: FpBaselineEntry[] = [
  { file: "src/lib/seedFileSamples.ts", id: "command-injection", lineHash: "e5aa10162c73", line: 450, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/pr/[id]/page.tsx", id: "eval-exec", lineHash: "007720b07a0e", line: 32, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/risk-register/page.tsx", id: "eval-exec", lineHash: "68f4c45370fe", line: 236, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/violations/page.tsx", id: "eval-exec", lineHash: "843a9a6c16e1", line: 28, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/violations/page.tsx", id: "eval-exec", lineHash: "6b0a735908ba", line: 297, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/components/AIIntelligencePanel.tsx", id: "eval-exec", lineHash: "f680283ec27b", line: 40, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "e6934e5b9b89", line: 72, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "0d2804f64bb9", line: 78, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "eval-exec", lineHash: "4b71e6dc0829", line: 83, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "580c70b4f318", line: 482, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "2853b81a86ea", line: 483, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/ast.ts", id: "eval-exec", lineHash: "b57628b649a2", line: 498, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  { file: "src/lib/compliance.ts", id: "eval-exec", lineHash: "572897493573", line: 137, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/findingCatalog.ts", id: "eval-exec", lineHash: "a86b069f7612", line: 23, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "7bc2608ba37f", line: 241, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "5fb22922bd11", line: 242, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "49749f1929a2", line: 244, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "f1686fe6bf42", line: 247, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "16bda5d7c77c", line: 249, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seed.ts", id: "eval-exec", lineHash: "9adff12bee91", line: 254, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/seedFileSamples.ts", id: "eval-exec", lineHash: "992728c5f7fc", line: 598, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/threatCatalog.ts", id: "eval-exec", lineHash: "433c06deac29", line: 85, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "54f6f58bc7bd", line: 58, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "9c3804adbe8b", line: 59, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "eval-exec", lineHash: "b0125e05afb6", line: 60, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/taint/sanitizers.ts", id: "hallucinated-method-call", lineHash: "f103599fc91b", line: 126, severity: "medium",
    reason: "False positive: the detector cannot infer that `calleeText` is a `string` (it is a typed string parameter of sanitizerClears) and flags the real built-in String.prototype.split() as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/scanner.ts", id: "hallucinated-method-call", lineHash: "22a5d5b840fa", line: 1646, severity: "medium",
    reason: "False positive: the detector cannot infer an array-index expression's (e.g. arr[i], match[1]) element type and defaults to flagging real built-in String/Array/Object methods (.trim(), .split(), .toLowerCase(), .sort(), .charCodeAt(), etc.) as hallucinated. Confirmed a genuine built-in at this call site." },
  { file: "src/lib/seedFileSamples.ts", id: "hallucinated-method-call", lineHash: "c214a36398b3", line: 499, severity: "medium",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/components/NewScanPanel.tsx", id: "hardcoded-secret", lineHash: "03a1a70cc450", line: 55, severity: "high",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/seedFileSamples.ts", id: "insecure-deserialization", lineHash: "ea197b071a38", line: 422, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/pr/[id]/page.tsx", id: "insecure-randomness", lineHash: "a7c5a5fc3b90", line: 52, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "insecure-randomness", lineHash: "19b975d6ce0f", line: 115, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/vulnCatalog.ts", id: "jwt-none-alg", lineHash: "2c086b6c0303", line: 45, severity: "critical",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/lib/realtime.ts", id: "ldap-injection", lineHash: "fc10a9f0feed", line: 173, severity: "critical",
    reason: "This is a Supabase Postgres realtime channel filter string (`filter: `org_id=eq.${...}`), not an LDAP filter -- pure keyword collision on the word \"filter\"." },
  { file: "src/lib/licenseContamination.ts", id: "license-header-contamination", lineHash: "54f37ad57cd7", line: 106, severity: "medium",
    reason: "This is the license-detector's OWN pattern-definition string (a literal snippet of real MIT/BSD license text used to detect copied license headers elsewhere) -- self-matches its own regex." },
  { file: "src/lib/licenseContamination.ts", id: "license-header-contamination", lineHash: "27ae6dba759c", line: 110, severity: "medium",
    reason: "This is the license-detector's OWN pattern-definition string (a literal snippet of real MIT/BSD license text used to detect copied license headers elsewhere) -- self-matches its own regex." },
  { file: "src/components/NewScanPanel.tsx", id: "sql-injection", lineHash: "3123f0f4c285", line: 37, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/components/NewScanPanel.tsx", id: "sql-injection", lineHash: "c381c60f5f1c", line: 44, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/seedFileSamples.ts", id: "sql-injection", lineHash: "d93a626aea03", line: 69, severity: "critical",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/app/api/custom-roles/route.ts", id: "ssrf", lineHash: "44ed02815ff5", line: 128, severity: "critical",
    reason: "new URL(req.url).searchParams.get(\"id\") reads the DELETE request's own query string; the id only filters a custom_roles query (scoped to the caller's org). The route makes no outbound request." },
  { file: "src/app/api/alerts/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 60, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/analytics/trends/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 37, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/audit/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 10, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/auth/2fa/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 117, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/compliance-config/route.ts", id: "ssrf", lineHash: "2342f6ba5dfd", line: 7, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/evidence/collect/route.ts", id: "ssrf", lineHash: "b8fab07a11fb", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 37, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/sarif/route.ts", id: "ssrf", lineHash: "88790235158d", line: 22, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/export/signed/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 25, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/github-app/manifest/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 20, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/incidents/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 12, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/report/history/route.ts", id: "ssrf", lineHash: "2993b049c663", line: 19, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/retention/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 67, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/retention/route.ts", id: "ssrf", lineHash: "5ae001042f4e-1", line: 162, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/bulk/route.ts", id: "ssrf", lineHash: "420f90eb0480", line: 23, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/compare/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scans/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 20, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/[id]/route.ts", id: "ssrf", lineHash: "8526dad1cd65", line: 50, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/[id]/route.ts", id: "ssrf", lineHash: "8526dad1cd65-1", line: 79, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 60, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/scim/v2/Users/route.ts", id: "ssrf", lineHash: "281991ffdc72", line: 109, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/search/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 43, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/secrets/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 33, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/sla/trend/route.ts", id: "ssrf", lineHash: "66d543b2e1a5", line: 22, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/storage/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 26, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/storage/route.ts", id: "ssrf", lineHash: "a06d87cb9567", line: 122, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/stripe/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 17, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/team/route.ts", id: "ssrf", lineHash: "24bfb15488af", line: 167, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/usage/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 38, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/violations/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 14, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "6d987564a156", line: 41, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "1644e9155920", line: 81, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/webhooks/route.ts", id: "ssrf", lineHash: "44ed02815ff5", line: 129, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "279f69f82427", line: 28, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "f24484f95a04", line: 41, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/app/api/zapier/route.ts", id: "ssrf", lineHash: "5ae001042f4e", line: 168, severity: "critical",
    reason: "new URL(req.url) parses the INBOUND Next.js request's own URL to read query params/pathname/origin via url.searchParams.get(...) etc. -- never used as an outbound fetch/request target. Uniform pattern confirmed across every sampled route handler in this corpus." },
  { file: "src/lib/errors.ts", id: "verbose-error", lineHash: "2dffa306ce8c", line: 48, severity: "medium",
    reason: "This is safeError(), the app's own centralized safe-error-handling utility. err.stack is passed only to logger.error(...) (server-side structured logging) -- the client response (line 52-53) only ever receives { error: opts.code, message: opts.message, ref_id: refId }, a sanitized message with a correlation id. The detector flags proximity to \"stack\" without seeing that it never reaches the HTTP response." },
  { file: "src/app/api/docs/route.ts", id: "weak-cors", lineHash: "5ad176110a75", line: 6, severity: "medium",
    reason: "Public OpenAPI spec endpoint (GET-only, no auth/cookies/session data) -- wildcard CORS is intentional so external API tooling and documentation generators can fetch the spec cross-origin. No sensitive data is served here." },
  { file: "src/lib/seedFileSamples.ts", id: "weak-crypto", lineHash: "a6417ea270ec", line: 444, severity: "high",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  { file: "src/lib/vulnCatalog.ts", id: "weak-crypto", lineHash: "ea4abd0ebbe6", line: 115, severity: "high",
    reason: "UI/catalog/label content describing this vulnerability class to users (a string literal shown in the product's own vulnerability-description, SARIF-rule, or threat-catalog UI) -- not executable code containing the vulnerability itself." },
  { file: "src/app/audit/page.tsx", id: "xss", lineHash: "75c80b8c460e", line: 85, severity: "critical",
    reason: "The `I` helper is defined but never invoked anywhere in this file (confirmed: no JSX usage, no call site) -- its dangerouslySetInnerHTML can never execute with any value at runtime. Effectively dead code; worth a future cleanup, but not a live XSS sink." },
  { file: "src/app/docs/page.tsx", id: "xss", lineHash: "824f2ab04e15", line: 20, severity: "critical",
    reason: "Static CSS string passed to dangerouslySetInnerHTML with zero interpolated variables (a plain template literal, no ${...} expressions) -- no dynamic content of any kind ever reaches this call." },
  { file: "src/app/trust-score/page.tsx", id: "xss", lineHash: "31dca680a91f", line: 149, severity: "critical",
    reason: "`org` (the only interpolated value not locally computed from `score`) is derived from `effectiveData?.repos?.[0]?.repo.split(\"/\")[0]` -- a GitHub org/user login segment, which GitHub itself restricts to alphanumerics and hyphens (no HTML metacharacters possible through this path). Impact is also bounded to self-XSS: document.write runs in a window.open() popup the acting user opened for their own org, not a sink reachable by any other user. Accepted with this specific caveat, not templated -- revisit if `org` is ever sourced from a less-constrained field." },
  { file: "src/lib/ast.ts", id: "xss", lineHash: "a5a8570f0472", line: 484, severity: "critical",
    reason: "This line is inside a detector's own pattern-DEFINITION list (e.g. HIGH_RISKS) -- a regex literal used to detect this vulnerability class elsewhere in scanned code, not an actual occurrence of it in this file." },
  // Added by the PHP OWASP hardening phase -- confirmed the same
  // established false-positive root-cause classes above, not new classes.
  { file: "src/components/NewScanPanel.tsx", id: "php-missing-session-guard", lineHash: "fd30fa60098b", line: 44, severity: "medium",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  { file: "src/lib/scanner.ts", id: "php-missing-session-guard", lineHash: "517b20014080", line: 1406, severity: "medium",
    reason: "UI/catalog/label content describing this vulnerability class to users (this specific line is the finding's own `detail` message text, which literally contains the word \"unserialize()\" as documentation) -- not executable code performing the sensitive action itself." },
  { file: "src/lib/scanner.ts", id: "php-missing-session-guard", lineHash: "cbde63307e5f", line: 1430, severity: "medium",
    reason: "UI/catalog/label content describing this vulnerability class to users (this specific line is the finding's own `detail` message text, which literally contains the word \"unserialize()\" as documentation) -- not executable code performing the sensitive action itself." },
  { file: "src/lib/scanner.ts", id: "php-missing-session-guard", lineHash: "4c8b03ec7d7f", line: 5158, severity: "medium",
    reason: "UI/catalog/label content describing this vulnerability class to users (this line is FIX_MAP's own description string for this very id, which literally contains the word \"unserialize()\" as documentation) -- not executable code performing the sensitive action itself." },
  { file: "src/lib/seedFileSamples.ts", id: "php-missing-session-guard", lineHash: "cc95ca321ed2", line: 110, severity: "medium",
    reason: "This line is inside seedFileSamples.ts's demo/seed fixture content (a Python cursor.execute() SQL string) -- deliberately vulnerable-looking sample code used to seed demo scans, never executed as part of the application itself." },
  // Added while fixing a Go detector-gap report: PLACEHOLDER_VALUE_RE's
  // bare "password" marker (no word boundary) was silently suppressing any
  // secret value that merely CONTAINED "password" as a substring --
  // tightening it to \bpassword\b surfaced this real, previously-hidden
  // demo-content finding.
  { file: "src/components/NewScanPanel.tsx", id: "hardcoded-secret", lineHash: "713d0879d184", line: 32, severity: "critical",
    reason: "This line is inside an intentionally-vulnerable code SAMPLE embedded as product demo content in NewScanPanel.tsx (shown to users to illustrate what the scanner detects) -- never executed." },
  // Added with the JS/TS recall phase: the structural JWT check flags hand-rolled payload decoding.
  { file: "src/lib/jwt.ts", id: "jwt-none-alg", lineHash: "ba3a2f2a74f7", line: 14, severity: "critical",
    reason: "Reviewed: decodeJwtPayload is a documented decode-only helper (its header comment says it does NOT verify the signature and must only be used on tokens already verified via supabase.auth.getUser(), to read extra claims such as session_id). It is never used as an authorization decision on its own." },
  // Added with the Java BOLA PrincipalState work: same known array-index type-inference gap as the entries above.
];
