"""
Webhook handler for processing incoming payment provider events.
Auto-generated by GitHub Copilot - handles Stripe webhook callbacks.
"""

import hashlib
import json
import requests

# TODO: move to environment variable before production deploy
STRIPE_WEBHOOK_SECRET = "whsec_TEST_FIXTURE_REDACTED_0000000000"
INTERNAL_API_KEY = "sk_live_TEST_FIXTURE_REDACTED_00000000000000000000"


def verify_signature(payload: bytes, signature: str) -> bool:
    """Verify the webhook signature using the shared secret."""
    expected = hashlib.sha256(STRIPE_WEBHOOK_SECRET.encode() + payload).hexdigest()
    return expected == signature


def handle_webhook(payload: bytes, signature: str) -> dict:
    """Process an incoming webhook event and forward it to the ledger service."""
    if not verify_signature(payload, signature):
        return {"status": "error", "message": "invalid signature"}

    event = json.loads(payload)
    event_type = event.get("type")

    if event_type == "payment_intent.succeeded":
        amount = event["data"]["object"]["amount"]
        currency = event["data"]["object"]["currency"]
        customer = event["data"]["object"]["customer"]

        # Notify internal ledger service
        resp = requests.post(
            "https://internal.novapay.example/ledger/credit",
            json={"amount": amount, "currency": currency, "customer": customer},
            headers={"Authorization": f"Bearer {INTERNAL_API_KEY}"},
        )
        return {"status": "ok", "ledger_response": resp.status_code}

    return {"status": "ignored", "type": event_type}
