import { runScan, detectAIToolingArtifacts } from "@/lib/scanner";
import { analyzeGitProvenance } from "@/lib/gitProvenance";

describe("AI tooling artifact detection", () => {
  it("detects known AI coding-agent config/rule files", () => {
    const found = detectAIToolingArtifacts([
      "src/index.ts",
      ".cursorrules",
      ".windsurf/rules/style.md",
      "CLAUDE.md",
      ".github/copilot-instructions.md",
      ".aider.conf.yml",
      "AGENTS.md",
      "README.md",
    ]);

    const tools = found.map(f => f.tool).sort();
    expect(tools).toEqual([
      "AI Agents", "Aider", "Claude Code", "Cursor", "GitHub Copilot", "Windsurf",
    ]);
  });

  it("returns empty for repos with no AI tooling artifacts", () => {
    expect(detectAIToolingArtifacts(["src/index.ts", "README.md", "package.json"])).toEqual([]);
  });

  it("surfaces ai_tooling on the ScanOutput", () => {
    const result = runScan({
      repo: "test/ai-tooling", pr_number: 1, commit_sha: "abc1234", branch: "main",
      files: [
        { path: "CLAUDE.md", content: "# Project instructions" },
        { path: "src/index.ts", content: "export const x = 1;" },
      ],
    });

    expect(result.ai_tooling.some(a => a.tool === "Claude Code" && a.file === "CLAUDE.md")).toBe(true);
  });

  it("detects attribution markers in file content, not just config file paths", () => {
    const found = detectAIToolingArtifacts(
      ["src/feature.ts"],
      [{ path: "src/feature.ts", content: "// 🤖 Generated with [Claude Code]\nexport const x = 1;" }],
    );
    expect(found.some(f => f.tool === "Claude Code")).toBe(true);
  });

  it("detects a Copilot co-authorship trailer left in file content", () => {
    const found = detectAIToolingArtifacts(
      ["src/feature.ts"],
      [{ path: "src/feature.ts", content: "export const x = 1;\n// Co-Authored-By: GitHub Copilot" }],
    );
    expect(found.some(f => f.tool === "GitHub Copilot")).toBe(true);
  });

  it("does not false-positive on ordinary code content", () => {
    const found = detectAIToolingArtifacts(
      ["src/feature.ts"],
      [{ path: "src/feature.ts", content: "export function add(a: number, b: number) { return a + b; }" }],
    );
    expect(found).toEqual([]);
  });

  it("is backward compatible when called with paths only (no content argument)", () => {
    expect(detectAIToolingArtifacts(["src/index.ts", "README.md"])).toEqual([]);
  });

  it("runScan wires file content into tool detection, so a normal PR with an attribution comment now scores tool_evidence > 0", () => {
    const result = runScan({
      repo: "test/ai-tooling-content", pr_number: 2, commit_sha: "def5678", branch: "main",
      files: [
        { path: "src/feature.ts", content: "// Generated by GitHub Copilot\nexport const y = 2;" },
      ],
    });
    expect(result.evidence_breakdown.tool_evidence).toBeGreaterThan(0);
  });
});

describe("AI-era commit subject detection", () => {
  function logLine(subject: string): string {
    return `abc123def4567890|Jane Dev|jane@example.com|1700000000|G|${subject}`;
  }

  it("flags Co-Authored-By trailers for AI agents in the commit message", () => {
    const summary = analyzeGitProvenance(
      logLine("feat: add login flow Co-Authored-By: Claude <noreply@anthropic.com>"),
    );
    expect(summary.aiAuthoredCommits).toBe(1);
  });

  it("flags 'Generated with Claude Code' markers", () => {
    const summary = analyzeGitProvenance(
      logLine("fix: handle null case - 🤖 Generated with [Claude Code]"),
    );
    expect(summary.aiAuthoredCommits).toBe(1);
  });

  it("flags Windsurf/Devin/Aider/Cline tool mentions", () => {
    for (const tool of ["windsurf", "devin", "aider", "cline"]) {
      const summary = analyzeGitProvenance(logLine(`chore: refactor via ${tool} agent`));
      expect(summary.aiAuthoredCommits).toBe(1);
    }
  });

  it("does not flag ordinary human commit subjects", () => {
    const summary = analyzeGitProvenance(logLine("fix: correct off-by-one error in pagination"));
    expect(summary.aiAuthoredCommits).toBe(0);
  });
});
